/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Jan 03 00:48:33 2018. */

#include "adc_reading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AdcReadings_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, AdcReadings, reading1, reading1, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, AdcReadings, reading2, reading1, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, AdcReadings, reading3, reading2, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, AdcReadings, reading4, reading3, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
