/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed Jan 03 00:48:33 2018. */

#ifndef PB_ADC_READING_PB_H_INCLUDED
#define PB_ADC_READING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AdcReadings {
    uint32_t reading1;
    uint32_t reading2;
    uint32_t reading3;
    uint32_t reading4;
/* @@protoc_insertion_point(struct:AdcReadings) */
} AdcReadings;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AdcReadings_init_default                 {0, 0, 0, 0}
#define AdcReadings_init_zero                    {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AdcReadings_reading1_tag                 1
#define AdcReadings_reading2_tag                 2
#define AdcReadings_reading3_tag                 3
#define AdcReadings_reading4_tag                 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t AdcReadings_fields[5];

/* Maximum encoded size of messages (where known) */
#define AdcReadings_size                         24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ADC_READING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
